// Code generated by ent, DO NOT EDIT.

package translator

import (
	"time"
)

const (
	// Label holds the string label denoting the translator type in the database.
	Label = "translator"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameSha holds the string denoting the name_sha field in the database.
	FieldNameSha = "name_sha"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldAddressSha holds the string denoting the address_sha field in the database.
	FieldAddressSha = "address_sha"
	// FieldDetailsURL holds the string denoting the details_url field in the database.
	FieldDetailsURL = "details_url"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the translator in the database.
	Table = "translators"
)

// Columns holds all SQL columns for translator fields.
var Columns = []string{
	FieldID,
	FieldNameSha,
	FieldLanguage,
	FieldAddressSha,
	FieldDetailsURL,
	FieldLatitude,
	FieldLongitude,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
