// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/flexoid/translators-map-go/ent/schema"
	"github.com/flexoid/translators-map-go/ent/translator"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	translatorFields := schema.Translator{}.Fields()
	_ = translatorFields
	// translatorDescCreatedAt is the schema descriptor for created_at field.
	translatorDescCreatedAt := translatorFields[6].Descriptor()
	// translator.DefaultCreatedAt holds the default value on creation for the created_at field.
	translator.DefaultCreatedAt = translatorDescCreatedAt.Default.(func() time.Time)
	// translatorDescUpdatedAt is the schema descriptor for updated_at field.
	translatorDescUpdatedAt := translatorFields[7].Descriptor()
	// translator.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	translator.DefaultUpdatedAt = translatorDescUpdatedAt.Default.(func() time.Time)
	// translator.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	translator.UpdateDefaultUpdatedAt = translatorDescUpdatedAt.UpdateDefault.(func() time.Time)
}
