// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexoid/translators-map-go/ent/translator"
)

// TranslatorCreate is the builder for creating a Translator entity.
type TranslatorCreate struct {
	config
	mutation *TranslatorMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TranslatorCreate) SetName(s string) *TranslatorCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetLanguage sets the "language" field.
func (tc *TranslatorCreate) SetLanguage(s string) *TranslatorCreate {
	tc.mutation.SetLanguage(s)
	return tc
}

// SetAddress sets the "address" field.
func (tc *TranslatorCreate) SetAddress(s string) *TranslatorCreate {
	tc.mutation.SetAddress(s)
	return tc
}

// SetContacts sets the "contacts" field.
func (tc *TranslatorCreate) SetContacts(s string) *TranslatorCreate {
	tc.mutation.SetContacts(s)
	return tc
}

// SetDetailsURL sets the "details_url" field.
func (tc *TranslatorCreate) SetDetailsURL(s string) *TranslatorCreate {
	tc.mutation.SetDetailsURL(s)
	return tc
}

// SetLatitude sets the "latitude" field.
func (tc *TranslatorCreate) SetLatitude(f float64) *TranslatorCreate {
	tc.mutation.SetLatitude(f)
	return tc
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableLatitude(f *float64) *TranslatorCreate {
	if f != nil {
		tc.SetLatitude(*f)
	}
	return tc
}

// SetLongitude sets the "longitude" field.
func (tc *TranslatorCreate) SetLongitude(f float64) *TranslatorCreate {
	tc.mutation.SetLongitude(f)
	return tc
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableLongitude(f *float64) *TranslatorCreate {
	if f != nil {
		tc.SetLongitude(*f)
	}
	return tc
}

// Mutation returns the TranslatorMutation object of the builder.
func (tc *TranslatorCreate) Mutation() *TranslatorMutation {
	return tc.mutation
}

// Save creates the Translator in the database.
func (tc *TranslatorCreate) Save(ctx context.Context) (*Translator, error) {
	var (
		err  error
		node *Translator
	)
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TranslatorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Translator)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TranslatorMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TranslatorCreate) SaveX(ctx context.Context) *Translator {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TranslatorCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TranslatorCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TranslatorCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Translator.name"`)}
	}
	if _, ok := tc.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "Translator.language"`)}
	}
	if _, ok := tc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Translator.address"`)}
	}
	if _, ok := tc.mutation.Contacts(); !ok {
		return &ValidationError{Name: "contacts", err: errors.New(`ent: missing required field "Translator.contacts"`)}
	}
	if _, ok := tc.mutation.DetailsURL(); !ok {
		return &ValidationError{Name: "details_url", err: errors.New(`ent: missing required field "Translator.details_url"`)}
	}
	return nil
}

func (tc *TranslatorCreate) sqlSave(ctx context.Context) (*Translator, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tc *TranslatorCreate) createSpec() (*Translator, *sqlgraph.CreateSpec) {
	var (
		_node = &Translator{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: translator.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: translator.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: translator.FieldName,
		})
		_node.Name = value
	}
	if value, ok := tc.mutation.Language(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: translator.FieldLanguage,
		})
		_node.Language = value
	}
	if value, ok := tc.mutation.Address(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: translator.FieldAddress,
		})
		_node.Address = value
	}
	if value, ok := tc.mutation.Contacts(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: translator.FieldContacts,
		})
		_node.Contacts = value
	}
	if value, ok := tc.mutation.DetailsURL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: translator.FieldDetailsURL,
		})
		_node.DetailsURL = value
	}
	if value, ok := tc.mutation.Latitude(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: translator.FieldLatitude,
		})
		_node.Latitude = value
	}
	if value, ok := tc.mutation.Longitude(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: translator.FieldLongitude,
		})
		_node.Longitude = value
	}
	return _node, _spec
}

// TranslatorCreateBulk is the builder for creating many Translator entities in bulk.
type TranslatorCreateBulk struct {
	config
	builders []*TranslatorCreate
}

// Save creates the Translator entities in the database.
func (tcb *TranslatorCreateBulk) Save(ctx context.Context) ([]*Translator, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Translator, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TranslatorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TranslatorCreateBulk) SaveX(ctx context.Context) []*Translator {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TranslatorCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TranslatorCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
