// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexoid/translators-map-go/ent/translator"
)

// TranslatorCreate is the builder for creating a Translator entity.
type TranslatorCreate struct {
	config
	mutation *TranslatorMutation
	hooks    []Hook
}

// SetExternalID sets the "external_id" field.
func (tc *TranslatorCreate) SetExternalID(i int) *TranslatorCreate {
	tc.mutation.SetExternalID(i)
	return tc
}

// SetName sets the "name" field.
func (tc *TranslatorCreate) SetName(s string) *TranslatorCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableName(s *string) *TranslatorCreate {
	if s != nil {
		tc.SetName(*s)
	}
	return tc
}

// SetLanguage sets the "language" field.
func (tc *TranslatorCreate) SetLanguage(s string) *TranslatorCreate {
	tc.mutation.SetLanguage(s)
	return tc
}

// SetAddress sets the "address" field.
func (tc *TranslatorCreate) SetAddress(s string) *TranslatorCreate {
	tc.mutation.SetAddress(s)
	return tc
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableAddress(s *string) *TranslatorCreate {
	if s != nil {
		tc.SetAddress(*s)
	}
	return tc
}

// SetAddressSha sets the "address_sha" field.
func (tc *TranslatorCreate) SetAddressSha(b []byte) *TranslatorCreate {
	tc.mutation.SetAddressSha(b)
	return tc
}

// SetCity sets the "city" field.
func (tc *TranslatorCreate) SetCity(s string) *TranslatorCreate {
	tc.mutation.SetCity(s)
	return tc
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableCity(s *string) *TranslatorCreate {
	if s != nil {
		tc.SetCity(*s)
	}
	return tc
}

// SetAdministrativeArea sets the "administrative_area" field.
func (tc *TranslatorCreate) SetAdministrativeArea(s string) *TranslatorCreate {
	tc.mutation.SetAdministrativeArea(s)
	return tc
}

// SetNillableAdministrativeArea sets the "administrative_area" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableAdministrativeArea(s *string) *TranslatorCreate {
	if s != nil {
		tc.SetAdministrativeArea(*s)
	}
	return tc
}

// SetCountry sets the "country" field.
func (tc *TranslatorCreate) SetCountry(s string) *TranslatorCreate {
	tc.mutation.SetCountry(s)
	return tc
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableCountry(s *string) *TranslatorCreate {
	if s != nil {
		tc.SetCountry(*s)
	}
	return tc
}

// SetDetailsURL sets the "details_url" field.
func (tc *TranslatorCreate) SetDetailsURL(s string) *TranslatorCreate {
	tc.mutation.SetDetailsURL(s)
	return tc
}

// SetLatitude sets the "latitude" field.
func (tc *TranslatorCreate) SetLatitude(f float64) *TranslatorCreate {
	tc.mutation.SetLatitude(f)
	return tc
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableLatitude(f *float64) *TranslatorCreate {
	if f != nil {
		tc.SetLatitude(*f)
	}
	return tc
}

// SetLongitude sets the "longitude" field.
func (tc *TranslatorCreate) SetLongitude(f float64) *TranslatorCreate {
	tc.mutation.SetLongitude(f)
	return tc
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableLongitude(f *float64) *TranslatorCreate {
	if f != nil {
		tc.SetLongitude(*f)
	}
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TranslatorCreate) SetCreatedAt(t time.Time) *TranslatorCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableCreatedAt(t *time.Time) *TranslatorCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TranslatorCreate) SetUpdatedAt(t time.Time) *TranslatorCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TranslatorCreate) SetNillableUpdatedAt(t *time.Time) *TranslatorCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// Mutation returns the TranslatorMutation object of the builder.
func (tc *TranslatorCreate) Mutation() *TranslatorMutation {
	return tc.mutation
}

// Save creates the Translator in the database.
func (tc *TranslatorCreate) Save(ctx context.Context) (*Translator, error) {
	tc.defaults()
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TranslatorCreate) SaveX(ctx context.Context) *Translator {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TranslatorCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TranslatorCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TranslatorCreate) defaults() {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		v := translator.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		v := translator.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TranslatorCreate) check() error {
	if _, ok := tc.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "Translator.external_id"`)}
	}
	if _, ok := tc.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "Translator.language"`)}
	}
	if _, ok := tc.mutation.AddressSha(); !ok {
		return &ValidationError{Name: "address_sha", err: errors.New(`ent: missing required field "Translator.address_sha"`)}
	}
	if _, ok := tc.mutation.DetailsURL(); !ok {
		return &ValidationError{Name: "details_url", err: errors.New(`ent: missing required field "Translator.details_url"`)}
	}
	return nil
}

func (tc *TranslatorCreate) sqlSave(ctx context.Context) (*Translator, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TranslatorCreate) createSpec() (*Translator, *sqlgraph.CreateSpec) {
	var (
		_node = &Translator{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(translator.Table, sqlgraph.NewFieldSpec(translator.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.ExternalID(); ok {
		_spec.SetField(translator.FieldExternalID, field.TypeInt, value)
		_node.ExternalID = value
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(translator.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Language(); ok {
		_spec.SetField(translator.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := tc.mutation.Address(); ok {
		_spec.SetField(translator.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := tc.mutation.AddressSha(); ok {
		_spec.SetField(translator.FieldAddressSha, field.TypeBytes, value)
		_node.AddressSha = value
	}
	if value, ok := tc.mutation.City(); ok {
		_spec.SetField(translator.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := tc.mutation.AdministrativeArea(); ok {
		_spec.SetField(translator.FieldAdministrativeArea, field.TypeString, value)
		_node.AdministrativeArea = value
	}
	if value, ok := tc.mutation.Country(); ok {
		_spec.SetField(translator.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := tc.mutation.DetailsURL(); ok {
		_spec.SetField(translator.FieldDetailsURL, field.TypeString, value)
		_node.DetailsURL = value
	}
	if value, ok := tc.mutation.Latitude(); ok {
		_spec.SetField(translator.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := tc.mutation.Longitude(); ok {
		_spec.SetField(translator.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(translator.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(translator.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TranslatorCreateBulk is the builder for creating many Translator entities in bulk.
type TranslatorCreateBulk struct {
	config
	err      error
	builders []*TranslatorCreate
}

// Save creates the Translator entities in the database.
func (tcb *TranslatorCreateBulk) Save(ctx context.Context) ([]*Translator, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Translator, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TranslatorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TranslatorCreateBulk) SaveX(ctx context.Context) []*Translator {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TranslatorCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TranslatorCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
