// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Translator is the predicate function for translator builders.
type Translator func(*sql.Selector)
